name: sencare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_slidable: ^4.0.0
  scroll_picker: ^0.0.2
  http: ^1.3.0
  


dev_dependencies:
  test: ^1.25.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
